### ISSUE TITLE
Docker image

### ISSUE THREAD

**Issue by roderik** [maticnetwork/turbo-bor#17]
# Rationale

Why should this feature exist?

makes it easy to play around with it

What are the use-cases?

k8s deploys, archive nodes on bor are not fun, need more speed....

# Implementation

Do you have ideas regarding the implementation of this feature?

github actions is easy to do

Are you willing to implement this feature?

I can do an initial code share, secrets need to be handled by you

Throw this in the gha flow and it will make containers on ghcr and dockerhub tagged with branch name, version numbers if on tags, for every commit a sha tag to pick specific containers of specific builds

```
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            ghcr.io/maticnetwork/turbo-bor
            maticnetwork/turbo-bor
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_PASS }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.PAT_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          file: ./Dockerfile
          cache-from: type=registry,ref=ghcr.io/maticnetwork/turbo-bor:buildcache
          cache-to: type=registry,ref=ghcr.io/maticnetwork/turbo-bor:buildcache,mode=max
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
```

ps. can turbo-bor be used already or is it not ready?
